### ISSUE TITLE
Expired discord invite link

### ISSUE THREAD

**Issue by pranav-singhal** [yomi-digital/website#3]
Hey team

Found your website through EthRome. Just wanted to let you know that the discord link in your website is expired
![Screenshot 2023-10-06 at 4 11 09 PM](https://github.com/yomi-digital/website/assets/29460541/b187f6f0-f1f3-473f-9fee-e28bde9fe0dd)

**Comment by llivio** [comment]
@pranav-singhal  Thank you for the feedback. Fixed!

**Comment by pranav-singhal** [comment]
Thanks
Closing this task
